### ISSUE TITLE
Turkish spell checking for Emacs?

### ISSUE THREAD

**Issue by ofenerci** [emres/turkish-mode#6]
Hello,
I wonder there is a spell-checking mode for Turkish documents?

**Comment by emres** [comment]
I'm afraid I don't know the state of the art when it comes to easy spell checking for Turkish on Emacs, but I'd start with the following:

- http://hrzafer.com/hunspell-tr
- https://github.com/Slyneth/hunspell-hyphenation-turkish
- https://github.com/titoBouzout/Dictionaries
- https://www.emacswiki.org/emacs/InteractiveSpell#toc7
- https://passingcuriosity.com/2017/emacs-hunspell-and-dictionaries/
- https://code.google.com/archive/p/tr-spell/

Of course, you'll be better of asking your question at https://emacs.stackexchange.com, https://lists.gnu.org/mailman/listinfo/help-gnu-emacs, or https://groups.google.com/forum/#!forum/comp.emacs

Therefore, I'm closing this non-issue.
